/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A virtual repository where data is stored, such as aws-s3-bucket, aws-rds-cluster, aws-dynamodb-table, bitbucket-repo, sharepoint-site, docker-registry. The exact type is described in the _type property of the Entity.
 */
export type DataStore = Entity & {
  /**
   * URI to the data store, e.g. https://docker-registry.jupiterone.com or https://jupiterone.sharepoint.com. Or a description to the physical location.
   */
  location?: string;
  /**
   * If the data needs to be encrypted
   */
  encryptionRequired?: boolean;
  /**
   * Encryption algorithm used to encrypt the data store
   */
  encryptionAlgorithm?: string;
  /**
   * Reference to the encryption key used to encrypt the data store
   */
  encryptionKeyRef?: string;
  /**
   * If the data store is encrypted
   */
  encrypted: boolean | null;
  /**
   * Indicates if the data store is open to public access
   */
  public?: boolean;
  /**
   * Indicates if the data store is data backup has been configured/enabled.
   */
  hasBackup?: boolean;
  /**
   * The number of days for which data is retained
   */
  retentionPeriodDays?: number;
  [k: string]: unknown;
};
