/* eslint-disable */
import { EntityJson } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The DNS Zone of an Internet Domain.
 */
export type DomainZoneJson = EntityJson & {
  /**
   * Domain name.
   */
  domainName: string;
  /**
   * Parent domain, if the entity is a sub-domain.
   */
  parent?: string;
  /**
   * Total number of DNS records in this zone.
   */
  recordsCount?: number;
  [k: string]: unknown;
};
