/* eslint-disable */
import { RecordEntity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A security finding, which may be a vulnerability or just an informative issue. A single finding may impact one or more resources. The `IMPACTS` relationship between the Vulnerability and the resource entity that was impacted serves as the record of the finding. The `IMPACTS` relationship carries properties such as 'identifiedOn', 'remediatedOn', 'remediationDueOn', 'issueLink', etc.
 */
export type Finding = RecordEntity & {
  /**
   * The category of the finding.
   */
  category: string | string[];
  /**
   * The name/id of the assessment that produced this finding.
   */
  assessment?: string;
  /**
   * Status of the vulnerability
   */
  status?: string;
  /**
   * Severity rating based on impact and exploitability.
   */
  severity: string;
  /**
   * Severity rating based on impact and exploitability.
   */
  numericSeverity: number;
  /**
   * Priority level mapping to Severity rating. Can be a string such as 'critical', 'high', 'medium', 'low', 'info'.  Or an integer usually between 0-5.
   */
  priority?: string;
  /**
   * The overall vulnerability score, e.g. CVSSv3.
   */
  score?: number;
  /**
   * The impact description or rating.
   */
  impact?: string;
  /**
   * The exploitability score/rating.
   */
  exploitability?: number;
  /**
   * The vulnerability attack vector. (e.g. a CVSSv3 vector looks like this - 'AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N')
   */
  vector?: string;
  /**
   * Steps to reproduce this finding.
   */
  stepsToReproduce?: string[];
  /**
   * Recommendation on how to remediate/fix this finding.
   */
  recommendation?: string;
  /**
   * The target listing of projects, applications, repos or systems this vulnerability impacts. Specifying either the project/repo name or the application URL here will auto-map this Vulnerability to the corresponding Project/CodeRepo/Application entity if a match is found.
   */
  targets?: string[];
  /**
   * Additional details about the targets. Can be a string or an array.
   */
  targetDetails?: string[];
  /**
   * The number of days that the Vulnerability must be remediated within, based on SLA set by the organization's internal vulnerability management program policy. The actually due date is set by 'remediationDueOn' property on the `IMPACTS` relationship between the Vulnerability and its impacted resource entity.
   */
  remediationSLA?: number;
  /**
   * Indicates whether this vulnerability finding is a blocking issue. If true, it should block a production deploy. Defaults to false.
   */
  blocksProduction?: boolean;
  /**
   * Indicates if this is an open vulnerability.
   */
  open: boolean;
  /**
   * Indicates if this vulnerability is in production.
   */
  production?: boolean;
  /**
   * Indicates if this is a publicly disclosed vulnerability. If yes, this is usually a CVE and the 'webLink' should be set to 'https://nvd.nist.gov/vuln/detail/${CVE-Number}' or to a vendor URL. If not, it is most likely a custom application vulnerability.
   */
  public?: boolean;
  /**
   * Indicates if this Vulnerability finding has been validated by the security team.
   */
  validated?: boolean;
  /**
   * The array of links to references.
   */
  references?: string[];
  [k: string]: unknown;
};
