/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Standard metadata properties of a graph object, maintained by the system. These are visible to users but may not be directly modified.
 */
export interface GraphObject {
  /**
   * An identifier unique within the scope containing the object. For example, for a Bitbucket repo, this will be the GUID of the repo as assigned by Bitbucket. For an IAM Role, this will be the ARN of the role.
   */
  _key: string;
  /**
   * One or more classes conforming to a standard, abstract security data model. For example, an EC2 instance will have '_class':'Host'.
   */
  _class: string | [string, ...string[]];
  /**
   * The type of object, typically reflecting the vendor and resource type. For example, 'aws_iam_user'. In some cases, a system knows about a type of entity that other systems know about, such as 'user_endpoint' or 'cve'.
   */
  _type: string;
  /**
   * Named tags assigned to the entity (i.e., 'tag.Name', 'tag.OtherName')
   *
   * This interface was referenced by `GraphObject`'s JSON-Schema definition
   * via the `patternProperty` "^tag\.".
   */
  [k: string]: string | number | boolean;
}
