/* eslint-disable */
import { RecordEntityJson } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A security weakness.
 */
export type WeaknessJson = RecordEntityJson & {
  /**
   * The category of the vulnerability finding
   */
  category?: string;
  /**
   * Indicates the likelihood of exploit.
   */
  exploitability?: string;
  /**
   * The array of links to references.
   */
  references?: string[];
  [k: string]: unknown;
};
